const quosAirTables = {
    quos_product: "quos_product",
    address: "address",
    qa_customer_right: "qa_customer_right",
    qa_user_right: "qa_user_right",
    qa_data_type: "qa_data_type",
    qa_pn_product: "qa_pn_product",
    qa_sensor: "qa_sensor",
    qa_sensor_param: "qa_sensor_param",
    qa_sensor_date: "qa_sensor_date",
    qa_sensor_threshold: "qa_sensor_threshold",
    qa_group: "qa_group",
    qa_sensor_group: "qa_sensor_group",
    qa_room_type: "qa_room_type",
    qa_building: "qa_building",
    qa_sensor_location: "qa_sensor_location",
    qa_lorawan_network: "qa_lorawan_network",
    qa_icone: "qa_icone",
    qa_downlink_mode: "qa_downlink_mode",
    qa_downlink: "qa_downlink",
    qa_qai_external_condition: "qa_qai_external_condition",
    qa_qai_particular_event: "qa_qai_particular_event",
    qa_qai_pack: "qa_qai_pack",
    qa_evt_attribution: "qa_evt_attribution",
    qa_evt: "qa_evt",
    qa_evt_co2: "qa_evt_co2",
    qa_evt_temperature: "qa_evt_temperature",
    qa_evt_humidity: "qa_evt_humidity",
    qa_analysis_type: "qa_analysis_type",
    qa_target_type: "qa_target_type",
    qa_analysis: "qa_analysis",
    qa_sensor_analysis: "qa_sensor_analysis",
    qa_building_analysis: "qa_building_analysis",
    qa_group_analysis: "qa_group_analysis",
    qa_report: "qa_report",
    qa_report_room: "qa_report_room",
    qa_report_analysis: "qa_report_analysis",
    qa_sensor_report: "qa_sensor_report",
    qa_building_report: "qa_building_report",
    qa_group_report: "qa_group_report",
    qa_report_to_user: "qa_report_to_user",
    qa_alert: "qa_alert",
    qa_alert_mail_history: "qa_alert_mail_history",
    qa_user_to_alert: "qa_user_to_alert",
    qa_customer_right:"qa_customer_right",
    qa_user_right:"qa_user_right",
};

module.exports = quosAirTables; 